name: CI/CD

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write  # <--- This is essential for GHCR push to work

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}  # <--- Built-in token

      - name: Build and Push ETL image
        run: |
          docker build -t ghcr.io/amirrezaKha/ml-etl:latest ./data-pipeline
          docker push ghcr.io/amirrezaKha/ml-etl:latest

      - name: Build and Push Model Trainer image
        run: |
          docker build -t ghcr.io/amirrezaKha/ml-trainer:latest ./model-trainer
          docker push ghcr.io/amirrezaKha/ml-trainer:latest

      - name: Build and Push API image
        run: |
          docker build -t ghcr.io/amirrezaKha/ml-api:latest ./model-api
          docker push ghcr.io/amirrezaKha/ml-api:latest

      - name: Set up Kind cluster
        uses: helm/kind-action@v1.8.0

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Deploy to K8s with Helm
        run: |
          helm upgrade --install ml-pipeline ./k8s-helm --namespace default --create-namespace
