name: CI/CD

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      # Removed packages: write since no pushing

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build ETL image
        run: |
          docker build -t ghcr.io/amirrezakha/ml-etl:latest ./data-pipeline

      - name: Build Model Trainer image
        run: |
          docker build -t ghcr.io/amirrezakha/ml-trainer:latest ./model-trainer

      - name: Build API image
        run: |
          docker build -t ghcr.io/amirrezakha/ml-api:latest ./model-api

      - name: Set up Kind cluster
        uses: helm/kind-action@v1.8.0

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Deploy to K8s with Helm
        run: |
          helm upgrade --install ml-pipeline ./k8s-helm --namespace default --create-namespace
