name: CI/CD

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push ETL
        run: |
          docker build -t ghcr.io/amirrezakha/ml-etl:latest ./data-pipeline
          docker push ghcr.io/amirrezakha/ml-etl:latest

      - name: Build and Push Trainer
        run: |
          docker build -t ghcr.io/amirrezakha/ml-trainer:latest ./model-trainer
          docker push ghcr.io/amirrezakha/ml-trainer:latest

      - name: Build and Push API
        run: |
          docker build -t ghcr.io/amirrezakha/ml-api:latest ./model-api
          docker push ghcr.io/amirrezakha/ml-api:latest

      - name: Set up K8s
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Helm Upgrade
        run: |
          helm upgrade --install ml-pipeline ./k8s-helm --namespace default